version: 0.2
phases:
  post_build:
    commands:
      - aws s3 sync . s3://alexgafita.com --delete
      - aws cloudfront create-invalidation --distribution-id E2ZOISQRSSWJTF --paths "/*"
artifacts:
  files:
    - '**/*'